### ISSUE TITLE
Cannot compile for ESP8266

### ISSUE THREAD

**Issue by sany3001** [jordancrubin/watermeter#1]
\Arduino\libraries\Watermeter\Watermeter.cpp:13:20: fatal error: SPIFFS.h: No such file or directory

 #include <SPIFFS.h>

                    ^

compilation terminated.

exit status 1
Error compiling for board WeMos D1 R1.

**Comment by jordancrubin** [comment]
I do not work with the 8266 but a quick google shows that 8266 requires an added include
#include <FS.h>   // Include the SPIFFS library
